<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:atom="http://www.w3.org/2005/Atom"
                xmlns:cap="urn:oasis:names:tc:emergency:cap:1.2">

  <xsl:output method="html" indent="yes" encoding="UTF-8"
              doctype-system="about:legacy-compat"/>

  <xsl:template match="/atom:feed">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title><xsl:value-of select="atom:title"/></title>
        <style>
          :root {
            --bg: #f4f6f8;
            --card: #ffffff;
            --text: #1f2d3d;
            --muted: #6b7a8f;
            --accent: #c0392b;
            --accent-soft: #fdecea;
            --border: #e1e5ea;
          }
          * { box-sizing: border-box; }
          html, body { margin: 0; padding: 0; }
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
                         "Helvetica Neue", Arial, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.5;
          }
          header {
            background: var(--accent);
            color: #fff;
          }
          .wrap {
            max-width: 960px;
            margin: 0 auto;
            padding: 1.5rem 1rem;
          }
          header h1 {
            margin: 0;
            font-size: 1.4rem;
            font-weight: 600;
          }
          header .rights {
            margin: 0.35rem 0 0;
            opacity: 0.85;
            font-size: 0.85rem;
          }
          main.wrap { padding-top: 1.5rem; padding-bottom: 3rem; }
          .meta {
            color: var(--muted);
            font-size: 0.85rem;
            margin: 0 0 1.25rem;
          }
          .entries {
            display: grid;
            gap: 0.9rem;
          }
          .entry {
            background: var(--card);
            border: 1px solid var(--border);
            border-left: 4px solid var(--accent);
            border-radius: 6px;
            padding: 0.9rem 1.1rem;
            box-shadow: 0 1px 2px rgba(0,0,0,0.04);
          }
          .entry h2 {
            margin: 0 0 0.4rem;
            font-size: 1.02rem;
            font-weight: 600;
            color: var(--accent);
          }
          .entry p {
            margin: 0.2rem 0;
          }
          .entry .summary {
            white-space: pre-line;
            margin: 0.4rem 0 0.2rem;
          }
          .entry .times {
            color: var(--muted);
            font-size: 0.82rem;
            margin-top: 0.5rem;
          }
          .entry a.cap {
            display: inline-block;
            margin-top: 0.6rem;
            color: var(--accent);
            font-size: 0.88rem;
            text-decoration: none;
          }
          .entry a.cap:hover { text-decoration: underline; }
          .empty {
            background: var(--card);
            border: 1px dashed var(--border);
            border-radius: 6px;
            padding: 2rem 1rem;
            text-align: center;
            color: var(--muted);
          }
          footer.wrap {
            color: var(--muted);
            font-size: 0.8rem;
            padding-top: 0;
          }
          footer.wrap a { color: var(--muted); }
        </style>
      </head>
      <body>
        <header>
          <div class="wrap">
            <h1><xsl:value-of select="atom:title"/></h1>
            <p class="rights"><xsl:value-of select="atom:rights"/></p>
          </div>
        </header>
        <main class="wrap">
          <p class="meta">
            Generated by <xsl:value-of select="atom:generator"/>.
            Last updated <xsl:value-of select="atom:updated"/>.
          </p>

          <xsl:variable name="alerts" select="atom:entry[cap:effective]"/>
          <xsl:choose>
            <xsl:when test="$alerts">
              <div class="entries">
                <xsl:for-each select="$alerts">
                  <div class="entry">
                    <h2><xsl:value-of select="atom:title"/></h2>
                    <p class="summary"><xsl:value-of select="atom:summary"/></p>
                    <p class="times">
                      Effective <xsl:value-of select="cap:effective"/>
                      &#8212; expires <xsl:value-of select="cap:expires"/>
                    </p>
                    <a class="cap" href="{atom:link/@href}">
                      View full CAP alert &#8594;
                    </a>
                  </div>
                </xsl:for-each>
              </div>
            </xsl:when>
            <xsl:otherwise>
              <div class="empty">
                <xsl:value-of select="atom:entry/atom:title"/>
              </div>
            </xsl:otherwise>
          </xsl:choose>
        </main>
        <footer class="wrap">
          <a href="{atom:link[@rel='self']/@href}">Raw ATOM feed</a>
        </footer>
      </body>
    </html>
  </xsl:template>

</xsl:stylesheet>
