name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1  # shallow clone
        submodules: false
        clean: true
        persist-credentials: false
    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Docker build
      run: docker build . --file Dockerfile --tag fmidev/smartmetalert:latest
    - name: Docker tag
      run: docker image tag fmidev/smartmetalert:latest fmidev/smartmetalert:$(date +%y.%m.%d)
    - name: Docker push
      run: docker push --all-tags fmidev/smartmetalert
